### ISSUE TITLE
Mobs despawning in spectator mode

### ISSUE THREAD

**Issue by Stabington** [MinervaMc/Datapacks#7]
All mobs will despawn when I go into spectator mode if I'm the only player around.
Annoying when troubleshooting mob farms, and could potentially be used as a cheat to remove mobs while exploring.

Would be neat if it could spawn a ghost player or something to prevent mobs from despawning. Don't know if this is even possible.

**Comment by Pablete1234** [comment]
With vanilla commands/datapack, this is impossible as of 1.15.2, and i doubt it will become possible anytime soon
